# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

stages:
- stage: api-live
  displayName: 'Test the API server is live'
  jobs:
  - job: test
    steps:
    - script: |
        portman -l weather.yaml -c portman-config.json

- stage: schema-validation
  dependsOn: [] 
  displayName: 'Validate schema from API server'
  jobs:
  - job: test
    steps:
    - script: |
        portman -l weather.yaml -c portman-config-schema-validation.json
